import React from "react";
import "./App.css";

import EasyTable from "Data/EasyTable";

const App = (props) => {
  return (
    <div style={{ flexGrow: 1 }}>
      <EasyTable
        edit={true}
        dataObj={sampledata}
        tbsetting={{ size: "small" }}
      />
    </div>
  );
};

export default App;

const sampledata = {
  key: "ext5",
  title: "Partition Vector",
  type: "table",
  dtorigin: [
    { Partition: 2 },
    { Partition: 1 },
    { Partition: 1 },
    { Partition: 1 },
    { Partition: 1 },
    { Partition: 1 },
    { Partition: 1 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 1 },
    { Partition: 2 },
    { Partition: 1 },
    { Partition: 2 },
    { Partition: 1 },
    { Partition: 1 },
    { Partition: 1 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 1 },
    { Partition: 1 },
    { Partition: 1 },
    { Partition: 1 },
  ],
  setting: {
    column: [
      {
        title: "Partition",
        titletext: "Partition",
        origin: "Partition",
        dataIndex: "Partition",
        key: "Partition",
        datatype: "int",
      },
    ],
    reset: false,
    title: "Partition Vector",
    size: "small",
  },
  id: "210317132524",
  checked: true,
  x: 6,
  y: 0,
  w: 6,
  h: 14,
  i: "1",
  dtlist: [
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 1 },
    { Partition: 1 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 1 },
    { Partition: 1 },
    { Partition: 2 },
    { Partition: 1 },
    { Partition: 1 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 1 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 1 },
    { Partition: 2 },
    { Partition: 1 },
    { Partition: 2 },
    { Partition: 1 },
    { Partition: 2 },
    { Partition: 1 },
    { Partition: 1 },
    { Partition: 2 },
    { Partition: 1 },
    { Partition: 2 },
    { Partition: 1 },
    { Partition: 2 },
    { Partition: 1 },
    { Partition: 2 },
    { Partition: 1 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 1 },
    { Partition: 2 },
    { Partition: 1 },
    { Partition: 1 },
    { Partition: 1 },
    { Partition: 2 },
    { Partition: 1 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 1 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 1 },
    { Partition: 1 },
    { Partition: 2 },
    { Partition: 1 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 1 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 1 },
    { Partition: 1 },
    { Partition: 2 },
    { Partition: 1 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 1 },
    { Partition: 1 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 1 },
    { Partition: 1 },
    { Partition: 1 },
    { Partition: 2 },
    { Partition: 1 },
    { Partition: 1 },
    { Partition: 2 },
    { Partition: 2 },
    { Partition: 1 },
    { Partition: 2 },
  ],
};
